# Generated by Django 4.1.5 on 2023-03-05 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_personal_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_remove_schedule_unique_employee_work_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('purpose', models.CharField(max_length=200)),
                ('examination', models.TextField(null=True)),
                ('diagnosis', models.CharField(max_length=250, null=True)),
                ('advice', models.TextField(null=True)),
                ('prescription', models.TextField(null=True)),
                ('took_place', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(default='DOCTOR REMOVED', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(default='PATIENT REMOVED', on_delete=django.db.models.deletion.SET_DEFAULT, to='patients.patient')),
            ],
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('datetime', 'doctor'), name='unique_doctor_appointment', violation_error_message='Doctor already has an appointment atthis datetime!'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('datetime', 'patient'), name='unique_patient_appointment', violation_error_message='Patient already has an appointment at this datetime!'),
        ),
    ]
